### ISSUE TITLE
.gitignore problem

### ISSUE THREAD

**Issue by mustafaturgutt** [ChebanovDD/Match3-SDK#7]
If you are using .gitignore file from [unitygitignore](https://github.com/github/gitignore/blob/main/Unity.gitignore). This file include ".app" and if you want to push to the remote, folders in Match.App folder will be discarded in remote so you need to change the Match.App name (like Match.Application) or you need to comment ".app" word in the .gitignore file.

**Comment by ChebanovDD** [comment]
Hey there. The preferred way to use the package is to add it through the package manager. This way you will avoid any issues. But if you wanna use it locally, for some reason, you have to adapt your `.gitignore` file by removing any `.app` lines or renaming the `Match.App`folder.

P.S. If you have any questions, please use [discussions](https://github.com/ChebanovDD/Match3-SDK/discussions).
