### ISSUE TITLE
Unable to add package [com.chebanovdd.match3sdk@0.1.2]

### ISSUE THREAD

**Issue by wwj13255066256** [ChebanovDD/Match3-SDK#8]
## Minimal reproduction code and steps

[Package Manager Window] Unable to add package [com.chebanovdd.match3sdk@0.1.2]:
  Package com.chebanovdd.match3sdk@0.1.2 has invalid dependencies or related test packages:
    com.cysharp.unitask (dependency): Version 'git+https://github.com/Cysharp/UniTask.git' is invalid. Expected a 'SemVer' compatible value.

## Current result

A clear and concise description of the result.

**Comment by ChebanovDD** [comment]
First, you have to install the [UniTask](https://openupm.com/packages/com.cysharp.unitask/) package. Please read the [Installation](https://github.com/ChebanovDD/Match3-SDK#gear-installation) section carefully.
